name: Get GITHUB CONTEXT

on: [workflow_dispatch, push]

jobs:
  get-context:
    runs-on: windows-latest
    steps:
    - name: Dump GitHub Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
