# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "dev-*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: concurrency-python-app-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        echo "Checking for: Python syntax errors or undefined names"
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        echo "There are NO Python syntax errors or undefined names"
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        echo "------------------------------------"
        echo "Checking for: All errors as warnings"
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest src

  build-2:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        echo "Checking for: Python syntax errors or undefined names"
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        echo "There are NO Python syntax errors or undefined names"
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        echo "------------------------------------"
        echo "Checking for: All errors as warnings"
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest src

  build-3:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        echo "Checking for: Python syntax errors or undefined names"
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        echo "There are NO Python syntax errors or undefined names"
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        echo "------------------------------------"
        echo "Checking for: All errors as warnings"
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest src

  build-4:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        echo "Checking for: Python syntax errors or undefined names"
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        echo "There are NO Python syntax errors or undefined names"
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        echo "------------------------------------"
        echo "Checking for: All errors as warnings"
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest src

  build-5:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        echo "Checking for: Python syntax errors or undefined names"
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        echo "There are NO Python syntax errors or undefined names"
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        echo "------------------------------------"
        echo "Checking for: All errors as warnings"
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest src
